apiVersion: v1
kind: ConfigMap
metadata:
  name: agentura-config
  namespace: agentura
data:
  SKILLS_DIR: "/skills"
  AGENTURA_KNOWLEDGE_DIR: "/data/.agentura"
  EXECUTOR_URL: "http://executor:8000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "agentura"
  DB_NAME: "agentura"
