apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentura

resources:
  - namespace.yaml
  - deployment.yaml
  - ../../operator/config/crd/bases/agentura.io_skillexecutions.yaml
  - ../../operator/config/crd/bases/agentura.io_executionpolicies.yaml
  - ../../operator/config/rbac/role.yaml
